SET GENERATOR GENERADOR TO 0;
INSERT INTO PERMISOS (USUARIOS, CLIENTES, CREARSAM, PAGOSAM, CONSULTASAM, INFORMESECO)
 VALUES ('1', '1', '1', '1', '1', '1');--id=1

INSERT INTO PERMISOS (USUARIOS, CLIENTES, CREARSAM, PAGOSAM, CONSULTASAM, INFORMESECO)
 VALUES ('1', '1', '1', '1', '1', '0');--id=2
 
 
INSERT INTO USUARIOS (IDPERMISO, NOMBRES, APELLIDOS, LOGIN, CLAVE, ESTADO)
VALUES (1, 'Jhironsel', 'Diaz Almonte', 'Jhironsel', '1234', '1');--id=3

INSERT INTO PERMISOS (USUARIOS, CLIENTES, CREARSAM, PAGOSAM, CONSULTASAM, INFORMESECO)
VALUES ('1', '1', '1', '0', '0', '0');--id=4

INSERT INTO USUARIOS (IDPERMISO, NOMBRES, APELLIDOS, LOGIN, CLAVE, ESTADO)
VALUES (2, 'Jhadiel', 'Diaz Paniagua', 'Jhadiel', '1234', '1');--id=5

INSERT INTO TURNOS (IDUSUARIO, FECHACREADO, HORACREADO, AUTOCREAR, FECHACIERRE, HORACIERRE, ESTADO)
VALUES (3, CURRENT_DATE, CURRENT_TIME, '0', null, null, '1');--id=6


INSERT INTO CLIENTES (IDTURNO, CEDULA, NOMBRES, APELLIDOS, DIRECCION, 
                    TELEFONO, TELEFONO2, CORREO, FECHANACIMIENTO, FECHAINGRESO, ESTADO)
VALUES (6, '000-0000000-0', 'Generico', ' ', ' ', '(000) 000-0000', '(000) 000-0000', 
     ' ', CURRENT_DATE, current_date, '1');--id=7
          
INSERT INTO COLORES (DESCRIPCION, CODCOLOR1, CODCOLOR2, CODCOLOR3)
VALUES ('Normal', 240, 240, 240);--id=8 
INSERT INTO COLORES (DESCRIPCION, CODCOLOR1, CODCOLOR2, CODCOLOR3)
VALUES ('Verde', 0, 255, 0);--id=9 
INSERT INTO COLORES (DESCRIPCION, CODCOLOR1, CODCOLOR2, CODCOLOR3)
VALUES ('Rojo', 255, 0, 0);--id=10

INSERT INTO PLANSAM (DESCRIPCION, HASTA, PORCIENTO, PENALIDADFECHAINCUMPLIMIENTO, PENALIDAD, ESTADO)
VALUES ('Sam 1 -20', 20, 0.05, 0.07, 0.10, '1');--id=11


INSERT INTO SAMS (IDCLIENTE, IDPLANSAM, IDTURNO, FECHA_CREADO, HORA, ESTADO)
VALUES (7, 11, 6, current_date, current_time, 'A'); --id=12


INSERT INTO DETALLESAM (IDSAM, LINEA, NUMERO, IDTURNO, FECHAPAGO, HORA, ESTADO)
VALUES (12, 1, 15, 6, current_date, current_time, '1');--id=12 linea 1

INSERT INTO DETALLESAM (IDSAM, LINEA, NUMERO, IDTURNO, FECHAPAGO, HORA, ESTADO)
VALUES (12, 2, 17, 6, current_date, current_time, '1');--id=12 linea 2






























                              