
GRANT EXECUTE
 ON PROCEDURE ADMIN_GET_ID_FACTURA_NUEVA TO ROLE R_CAJERO GRANTED BY SYSDBA;

GRANT EXECUTE
 ON PROCEDURE ADMIN_SET_ROLE TO ROLE R_CAJERO GRANTED BY SYSDBA;
 
GRANT EXECUTE
 ON PROCEDURE PERM_BASICOS TO ROLE R_CAJERO GRANTED BY SYSDBA;
 
GRANT EXECUTE
 ON PROCEDURE PERM_CREAR_FACTURAS TO ROLE R_CAJERO GRANTED BY SYSDBA;
 
GRANT EXECUTE
 ON PROCEDURE SP_S_GET_TURNOS TO ROLE R_CAJERO GRANTED BY SYSDBA;





GRANT SELECT
 ON GET_M_FACTURAS TO ROLE R_CAJERO GRANTED BY SYSDBA;

GRANT SELECT
 ON GET_PERSONA_CLIENTES TO ROLE R_CAJERO GRANTED BY SYSDBA;
 
GRANT SELECT
 ON GET_ROL TO ROLE R_CAJERO GRANTED BY SYSDBA;

GRANT SELECT
 ON GET_TURNOS TO ROLE R_CAJERO GRANTED BY SYSDBA;
 
GRANT SELECT
 ON VS_PRIVILEGIO TO ROLE R_CAJERO GRANTED BY SYSDBA;

GRANT SELECT
 ON V_CATEGORIAS TO ROLE R_CAJERO GRANTED BY SYSDBA;

GRANT SELECT
 ON V_FOTO_PRODUCTO TO ROLE R_CAJERO GRANTED BY SYSDBA;

GRANT SELECT
 ON V_GENERALES TO ROLE R_CAJERO GRANTED BY SYSDBA;

GRANT SELECT
 ON V_M_FACTURAS TO ROLE R_CAJERO GRANTED BY SYSDBA;

GRANT SELECT
 ON V_PERSONAS TO ROLE R_CAJERO GRANTED BY SYSDBA;

GRANT SELECT
 ON V_PERSONAS_CLIENTES TO ROLE R_CAJERO GRANTED BY SYSDBA;

GRANT SELECT
 ON V_PRECIOS TO ROLE R_CAJERO GRANTED BY SYSDBA;

GRANT SELECT
 ON V_PRODUCTOS TO ROLE R_CAJERO GRANTED BY SYSDBA;
 
GRANT SELECT
 ON V_TURNOS TO ROLE R_CAJERO GRANTED BY SYSDBA;
 
GRANT SELECT
 ON V_T_DISTRITOS_MUNICIPALES TO ROLE R_CAJERO GRANTED BY SYSDBA;
 
GRANT SELECT
 ON V_T_E_S_SYS TO ROLE R_CAJERO GRANTED BY SYSDBA;
 
GRANT SELECT
 ON V_T_MUNICIPIOS TO ROLE R_CAJERO GRANTED BY SYSDBA;
 
GRANT SELECT
 ON V_T_PROVINCIAS TO ROLE R_CAJERO GRANTED BY SYSDBA;